name: 'Release .deb files'
on: release

jobs:
  release-bionic:
    runs-on: ubuntu-latest
    name: Build and Releasing deb for bionic
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/bionic
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: libnginx-mod-http-sxg-filter_1.14.0-0ubuntu1.6_amd64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-eoan:
    runs-on: ubuntu-latest
    name: Build and Releasing deb for eoan
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/eoan
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: libnginx-mod-http-sxg-filter_1.16.1-0ubuntu2_amd64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-buster:
    runs-on: ubuntu-latest
    name: Build and Releasing deb for buster
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/buster
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: libnginx-mod-http-sxg-filter_1.14.2-2+deb10u1_amd64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
